
package edu.berkeley.boinc.lite;

/**
 * @author mat
 *
 */
public class Notice {
	public int seqno = -1;
    public String title = "";
    public String description = "";
    public double create_time;
    public double arrival_time;     // when item arrived at client
    public boolean is_private;
    public String category = "";
        // assigned by RSS source.  Reserved values:
        // "client": generated by client
        // "server": scheduler RPC message
    public String link = "";
        // URL where original message can be seen, if any
    public String project_name;
        // if notice is associated with a project

    // the following fields used in client only (not reported to GUI)
    public String guid = "";
    public String feed_url = "";
        // URL of RSS feed, or blank
    public boolean keep = false;
}
